### ISSUE TITLE
Improve yaml variable substitution

### ISSUE THREAD

**Issue by jcthomassie** [jcthomassie/yurt#19]
- [x] Allow substitution of variables defined in build file
- [x] Remove shellexpand
- [ ] ~~Deserialize all strings with substitution~~

```yaml
repo:
  local: ${{ env.HOME }}/dotfiles
...
  - ${{ repo.local }}-rest-of-string  # variables defined in file
  - ${{ env.DOTS_REPO_ROOT }}-rest-of-string  # environment variables
```
