### ISSUE TITLE
Extract PackageManager specs to build file

### ISSUE THREAD

**Issue by jcthomassie** [jcthomassie/yurt#68]
Currently package manager interfaces are hard coded. Might be preferable to remove this and make them entirely user configurable.

Sample format:
```yaml
- !installer
    name: cargo
    install: cargo install ${{ package }}
    uninstall: cargo remove ${{ package }}
    is_installed: cargo install --list | grep '^${{ package }} v'
    bootstrap: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
